# https://github.com/grafana/loki/blob/main/clients/cmd/promtail/promtail-docker-config.yaml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # # 必要ならラベルでフィルタ
        # filters:
        #   - name: label
        #     values: ["logging=promtail"]
    relabel_configs:
      # コンテナ名を取り出して label に
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container
      # ログファイルパスを動的に設定
      - source_labels: ["__meta_docker_container_id"]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log
