# # https://grafana.com/docs/tempo/latest/configuration/manifest/
# https://grafana.com/docs/tempo/latest/setup/linux/#create-a-tempo-configuration-file
server:
  # HTTP API/UI 用（例: 3200）
  http_listen_address: "0.0.0.0"
  http_listen_port: 3200

  # gRPC API 用（デフォルト 9095）
  grpc_listen_address: "0.0.0.0"
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        # OTLP over HTTP/Protobuf
        http:
          endpoint: "0.0.0.0:4318"
        # OTLP over gRPC
        grpc:
          endpoint: "0.0.0.0:4317"

compactor:
  compaction:
    block_retention: 48h # configure total trace retention here

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: linux-microservices
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/write
        send_exemplars: true

storage:
  trace:
    # ローカルファイルに保存する場合の設定
    backend: local
    local:
      path: /var/tempo/traces
